apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: fullstackpro-dev-tls
spec:
  secretName: fullstackpro-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fullstackpro.dev
  dnsNames:
    - fullstackpro.dev
    - www.fullstackpro.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fullstackpro.dev
          - www.fullstackpro.dev
